openapi: 3.0.3

info:
  title: Bankomat Backeng For Frontend Service
  description: Bankomat Backeng For Frontend Service
  version: 1.0.0

servers:
  - url: http://localhost:8080/

tags:
  - name: public
  - name: callbacks
  - name: private
paths:
  /bankomat-bff/v1/bff-api/card-verification/:
    post:
      tags:
        - public
      summary: Check match between card and PIN code
      operationId: cardVerification
      parameters: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CardVerificationRequest'
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /bankomat-bff/v1/bff-api/withdrawal/:
    post:
      tags:
        - public
      summary: Withdrawal found from account
      operationId: withdrawal
      parameters: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WithdrawalRequest'
      responses:
        '202':
          description: Successful operation
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /bankomat-bff/v1/bff-api/card-eject/:
    post:
      tags:
        - public
      summary: Eject card from atm
      operationId: cardEject
      parameters: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CardEjectRequest'
      responses:
        '202':
          description: Successful operation
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /bankomat-bff/v1/bff-api/callback/card-verification/{transactionId}:
    get:
      tags:
        - callbacks
      summary: Callback after card verification process
      operationId: cardVerificationCallback
      parameters:
        - name: transactionId
          in: path
          description: ID of transaction
          required: true
          schema:
            type: string
            example: 3cca68c6-b44f-40ea-9a11-973291ee4b26
      responses:
        '202':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallbackCardVerification'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /bankomat-bff/v1/bff-api/callback/withdrawal/{transactionId}:
    get:
      tags:
        - callbacks
      summary: Callback after card withdrawal process
      operationId: withdrawalCallback
      parameters:
        - name: transactionId
          in: path
          description: ID of transaction
          required: true
          schema:
            type: string
            example: 3cca68c6-b44f-40ea-9a11-973291ee4b26
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallbackWithdrawal'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /bankomat-bff/v1/bff-api/callback/card-eject/{transactionId}:
    get:
      tags:
        - callbacks
      summary: Callback after card eject process
      operationId: cardEjectCallback
      parameters:
        - name: transactionId
          in: path
          description: ID of transaction
          required: true
          schema:
            type: string
            example: 3cca68c6-b44f-40ea-9a11-973291ee4b26
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallbackCardEject'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /bankomat-bff/v1/bff-api/atm/get-all:
    get:
      tags:
        - private
      summary: Get all atms
      description: Get all atms
      operationId: getAllAtms
      parameters: [ ]
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AtmResponseList'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /bankomat-bff/v1/bff-api/account/get-all:
    get:
      tags:
        - private
      summary: Get all accounts
      description: Get all accounts
      operationId: getAllAccounts
      parameters: [ ]
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponseList'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
components:
  schemas:
    CallbackCardVerification:
      type: object
      properties:
        isCompleted:
          type: boolean
          example: true
        error:
          $ref: '#/components/schemas/Error'
        response:
          $ref: '#/components/schemas/CardVerificationResponse'
    CallbackWithdrawal:
      type: object
      properties:
        isCompleted:
          type: boolean
          example: true
        error:
          $ref: '#/components/schemas/Error'
        response:
          $ref: '#/components/schemas/WithdrawalResponse'
    CallbackCardEject:
      type: object
      properties:
        isCompleted:
          type: boolean
          example: true
        error:
          $ref: '#/components/schemas/Error'
        response:
          $ref: '#/components/schemas/CardEjectResponse'
    Error:
      type: object
      properties:
        message:
          type: string
          example: "Card Expiration date is different"
    CardEjectRequest:
      type: object
      properties:
        accountId:
          type: string
          example: "3cca68c6-b44f-40ea-9a11-973291ee4b26"
          pattern: ^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$
        transactionId:
          type: string
          example: "3cca68c6-b44f-40ea-9a11-973291ee4b26"
          pattern: ^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$
    CardEjectResponse:
      type: object
      properties:
        message:
          type: string
          example: "Card ejection is completed"
    CardVerificationRequest:
      type: object
      properties:
        cardNumber:
          type: string
          example: "1234567890123456"
          pattern: ^[0-9]{16}$
        expirationDate:
          type: string
          example: "12/25"
          pattern: ^(0[1-9]|1[0-2])\/([0-9]{2})$
        cvv:
          type: string
          example: "123"
          pattern: ^[0-9]{3}$
        pin:
          type: string
          example: "9876"
          pattern: ^[0-9]{4}$
        transactionId:
          type: string
          example: "3cca68c6-b44f-40ea-9a11-973291ee4b26"
          pattern: ^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$
        atmId:
          type: string
          example: "3cca68c6-b44f-40ea-9a11-973291ee4b26"
          pattern: ^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$
    CardVerificationResponse:
      type: object
      properties:
        accountId:
          type: string
          example: "3cca68c6-b44f-40ea-9a11-973291ee4b26"
          pattern: ^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$
        token:
          type: string
          example: "3cca68c6-b44f-40ea-9a11-973291ee4b26"
          pattern: ^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$
    WithdrawalRequest:
      type: object
      properties:
        accountId:
          type: string
          example: "3cca68c6-b44f-40ea-9a11-973291ee4b26"
          pattern: ^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$
        atmId:
          type: string
          example: "3cca68c6-b44f-40ea-9a11-973291ee4b26"
          pattern: ^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$
        token:
          type: string
          example: "3cca68c6-b44f-40ea-9a11-973291ee4b26"
          pattern: ^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$
        amount:
          type: number
          format: float
          example: 100.0
          pattern: ^\s*\d+(\.\d+)?\s*$
        currency:
          type: string
          example: "CZK"
          pattern: ^[A-Z]{3}$
        transactionId:
          type: string
          example: "3cca68c6-b44f-40ea-9a11-973291ee4b26"
          pattern: ^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$
    WithdrawalResponse:
      type: object
      properties:
        message:
          type: string
          example: "Transaction completed successfully"
    AccountResponseList:
      type: array
      items:
        $ref: '#/components/schemas/AccountResponse'
    AccountResponse:
      type: object
      properties:
        id:
          type: string
          example: "3cca68c6-b44f-40ea-9a11-973291ee4b26"
        balance:
          type: number
          format: float
          example: "1000.10"
          pattern: ^\s*\d+(\.\d+)?\s*$
        token:
          type: string
          example: "3cca68c6-b44f-40ea-9a11-973291ee4b26"
          pattern: ^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$
        createdAt:
          type: string
          format: date-time
          example: 2023-11-30 15:25:53.423
        status:
          type: string
          enum:
            - "activated"
            - "deactivated"
            - "cancelled"
        lockedAt:
          type: string
          format: date-time
          example: 2023-11-30 15:25:53.423
        AccountTransactionResponseList:
          type: array
          items:
            $ref: '#/components/schemas/AccountTransactionResponse'
        CardResponseList:
          type: array
          items:
            $ref: '#/components/schemas/CardResponse'
    CardResponse:
      type: object
      properties:
        id:
          type: string
          example: "3cca68c6-b44f-40ea-9a11-973291ee4b26"
          pattern: ^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$
        cardNumber:
          type: string
          example: "1234567890123456"
          pattern: ^[0-9]{16}$
        expirationDate:
          type: string
          example: "12/25"
          pattern: ^(0[1-9]|1[0-2])\/([0-9]{2})$
        cvv:
          type: string
          example: "123"
          pattern: ^[0-9]{3}$
        pin:
          type: string
          example: "9876"
          pattern: ^[0-9]{4}$
        createdAt:
          type: string
          format: date-time
          example: 2023-11-30 15:25:53.423
        expiredAt:
          type: string
          format: date-time
          example: 2023-11-30 15:25:53.423
        CardTransactionResponseList:
          type: array
          items:
            $ref: '#/components/schemas/CardTransactionResponse'
    AtmResponseList:
      type: array
      items:
        $ref: '#/components/schemas/AtmResponse'
    AtmResponse:
      type: object
      properties:
        id:
          type: string
          example: "1"
        balance:
          type: number
          format: float
          example: "1000.10"
          pattern: ^\s*\d+(\.\d+)?\s*$
        AccountTransactionResponseList:
          type: array
          items:
            $ref: '#/components/schemas/AccountTransactionResponse'
        CardTransactionResponseList:
          type: array
          items:
            $ref: '#/components/schemas/CardTransactionResponse'
    AccountTransactionResponse:
      type: object
      properties:
        id:
          type: string
          example: "3cca68c6-b44f-40ea-9a11-973291ee4b26"
          pattern: ^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$
        amount:
          type: number
          format: float
          example: "1000.10"
          pattern: ^\s*\d+(\.\d+)?\s*$
        balanceBefore:
          type: number
          format: float
          example: "1000.10"
          pattern: ^\s*\d+(\.\d+)?\s*$
        balanceAfter:
          type: number
          format: float
          example: "1000.10"
          pattern: ^\s*\d+(\.\d+)?\s*$
        status:
          type: string
          enum:
            - "success"
            - "pending"
            - "cancelled"
            - "insufficientFunds"
            - "invalidCard"
            - "timeout"
            - "networkError"
        createdAt:
          type: string
          format: date-time
          example: 2023-11-30 15:25:53.423
    CardTransactionResponse:
      type: object
      properties:
        id:
          type: string
          example: "3cca68c6-b44f-40ea-9a11-973291ee4b26"
          pattern: ^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$
        status:
          type: string
          enum:
            - "success"
            - "pending"
            - "cancelled"
            - "insufficientFunds"
            - "invalidCard"
            - "timeout"
            - "networkError"
        createdAt:
          type: string
          format: date-time
          example: 2023-11-30 15:25:53.423
    ProblemDetails:
      type: object
      description: Error response for codes 4xx and 5xx
      required:
        - title
        - type
      properties:
        type:
          type: string
          description: "type"
        title:
          type: string
          description: "title"
        status:
          type: integer
          format: int32
          description: "status"
        detail:
          type: string
          description: "detail"
        instance:
          type: string
          description: "instance"
        embeded:
          $ref: '#/components/schemas/AppSpecificProblemDetails'
    AppSpecificProblemDetails:
      type: object
      description: "Specific problem details"
      required:
        - code
        - reason
      properties:
        code:
          type: string
          description: "code"
        reason:
          type: string
          description: "reason"
        message:
          type: string
          description: "message"
        status:
          type: integer
          format: int32
          description: "status"